/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--hana-primary)',
        'primary-strong': 'var(--hana-primary-dark)',
        primaryDark: 'var(--hana-primary-dark)',
        primaryLight: 'var(--hana-primary-light)',
        primaryText: 'var(--hana-primary-text)',
        accentPink: 'var(--hana-accent-pink)',
        accentBlue: 'var(--hana-accent-blue)',
        accentPurple: 'var(--hana-accent-purple)',
        surface: 'var(--bg-card)',
        'surface-muted': 'var(--bg-section)',
        surfaceMuted: 'var(--bg-section)',
        page: 'var(--bg-page)',
        section: 'var(--bg-section)',
        hero: 'var(--bg-hero)',
        heroProduct: 'var(--bg-hero-product)',
        text: 'var(--text-primary)',
        'text-muted': 'var(--text-tertiary)',
        muted: 'var(--text-tertiary)',
        secondary: 'var(--text-secondary)',
        tertiary: 'var(--text-tertiary)',
        disabled: 'var(--text-disabled)',
        'text-teal': 'var(--text-teal)',
        tealText: 'var(--text-teal)',
        'text-pink': 'var(--text-pink)',
        pinkText: 'var(--text-pink)',
        border: 'var(--border-default)',
        borderCard: 'var(--border-card)',
        divider: 'var(--divider)',
        positive: 'var(--color-positive)',
        negative: 'var(--color-negative)',
        warning: 'var(--color-warning)',
        info: 'var(--color-info)',
        hanaGray: {
          50: '#F8F8F8',
          100: '#F2F2F7',
          200: '#E5E5EA',
          400: '#C7C7CC',
          600: '#8E8E93',
          800: '#4A4A4A',
          900: '#1A1A1A',
        },
      },
      boxShadow: {
        card: 'var(--shadow-card)',
        soft: 'var(--shadow-card-lg)',
        cardLg: 'var(--shadow-card-lg)',
      },
      borderRadius: {
        card: 'var(--radius-card)',
        cardSm: 'var(--radius-card-sm)',
        pill: 'var(--radius-pill)',
      },
      fontFamily: {
        sans: ['var(--font-sans)'],
      },
      keyframes: {
        slideUpFade: {
          '0%':   { opacity: '0', transform: 'translateY(20px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        slideUpFade: 'slideUpFade 0.32s ease both',
      },
    },
  },
  plugins: [],
}

